const dummyProfile = {
  nickname: 'sanseong ko',
  point: 2003, //string or num
  registeredGoods: 3,
  meetingNum: 3,
  profileImg: 'url.url.com',
  registeredEmailStatus: false,
  tradeChatStatus: true,
  meetingChatStatus: true,
  noticeStatus: true,
};

const dummyProducts = {
  content: [
    {
      id: 1,
      productName: '지구 슈퍼 색연필 12색',
      tradingMethod: 'DIRECT',
      productCategory: '학용품',
      productCondition: 'SECOND_HAND',
      location: '도봉구 도봉동',
      tradingStatus: '거래완료',
      completedTradingDate: '2011.01.01',
      tradingType: 'EXCHANGE',
    },
    {
      id: 2,
      productName: '전자레인지',
      tradingMethod: 'DIRECT',
      productCategory: '주방가전',
      productCondition: 'NEW',
      location: '도봉구 도봉동',
      tradingStatus: '거래완료',
      completedTradingDate: '2024.02.16',
      tradingType: 'EXCHANGE',
      productImg: '',
    },
    {
      id: 3,
      productName: '가스레인지',
      tradingMethod: 'DIRECT',
      productCategory: '주방가전',
      productCondition: 'SECOND_HAND',
      location: '도봉구 도봉동',
      tradingStatus: '거래전',
      completedTradingDate: null,
      tradingType: 'SHARE',
      productImg: '',
    },
    {
      id: 4,
      productName: '지우개',
      tradingMethod: 'DIRECT',
      productCategory: '학용품',
      productCondition: 'SECOND_HAND',
      location: '도봉구 도봉동',
      tradingStatus: '거래전',
      completedTradingDate: null,
      tradingType: 'DEAL',
      productImg: '',
    },
    {
      id: 5,
      productName: '쿠쿠 전자레인지 뭐시기 귀찮으니 복붙으로',
      tradingMethod: 'DIRECT',
      productCategory: '학용품',
      productCondition: 'SECOND_HAND',
      location: '도봉구 도봉동',
      tradingStatus: '거래전',
      completedTradingDate: null,
      tradingType: 'SHARE',
      productImg: '',
    },
    {
      id: 6,
      productName: '쿠쿠 전자레인지 뭐시기 귀찮으니 복붙으로',
      tradingMethod: 'DIRECT',
      productCategory: '학용품',
      productCondition: 'SECOND_HAND',
      location: '도봉구 도봉동',
      tradingStatus: '거래완료',
      completedTradingDate: '2024.01.16',
      tradingType: 'SHARE',
      productImg: '',
    },
  ],
  count: 2,
};

export {dummyProfile, dummyProducts};
